return {
    FormatTime = util.FormatTime,
    NiceConcat = util.NiceConcat,
    Locs = {
        MODMAIL_CLOSETICKET = "Close ticket",
        MODMAIL_TICKETCLOSE_MESSAGE = "%s has closed the ticket, this channel will automatically be deleted %s",
        MODMAIL_TICKETOPENING_MESSAGE = "Hello %s, use this private channel to communicate with **%s** staff.",
        MODMAIL_TICKETOPENING_MESSAGE_MODERATION = "Hello %s, **%s** staff wants to communicate with you.",
        MODMAIL_TICKETMESSAGE = "Ticket message:",
        MODMAIL_LEFTSERVER = "%s left the server",
        MODMAIL_NOTACTIVETICKET = "You can only do this in an active ticket channel, %s.",
        MODMAIL_NOTAUTHORIZED = "You are not authorized to do that %s.",
        MODMAIL_TICKETCLOSED_CONFIRMATION = "✅ Ticket closed.",
        MODMAIL_OPENTICKET_BUTTON_LABEL = "Open a modmail ticket...",
        MODMAIL_FORM_TITLE = "Open a channel with the server staff",
        MODMAIL_FORM_DESCRIPTION_LABEL = "Please describe your issue in a few words:",
        MODMAIL_OPENTICKET_FORBIDDEN = "You are forbidden to open a ticket on this server",
        MODMAIL_OPENTICKET_NOTALLOWED = "You do not have the permission to open a ticket on this server",
        MODMAIL_OPENTICKET_NOTALLOWED_OTHERMEMBER = "You do not have the permission to open a ticket for someone else",
        MODMAIL_TICKEDOPENED = "✅ A modmail ticket has been created: %s.",

		MUTE_ERROR_NOT_PART_OF_GUILD = "%s is not on the server",
        MUTE_GUILD_MESSAGE = "%s has muted %s%s%s",
        MUTE_MUTE_FAILED = "❌ failed to mute %s: %s",
        MUTE_NOTAUTHORIZED = "❌ You cannot mute that user due to your lower permissions",
        MUTE_PRIVATE_MESSAGE = "You have been muted from **%s** by %s%s%s",
        MUTE_REASON = "for the following reason: %s",
        MUTE_THEY_WILL_BE_UNMUTED_IN = "They will be unmuted %s",
        MUTE_UNMUTE_FAILED = "❌ failed to unmute %s: %s",
        MUTE_UNMUTE_GUILD_MESSAGE = "%s has unmuted %s%s",
        MUTE_UNMUTE_MESSAGE = "You have been unmuted from **%s** by %s%s",
        MUTE_YOU_WILL_BE_UNMUTED_IN = "You will be unmuted %s",

        RAID_LOCKSERVER_HELP = "Locks the server, preventing people to join", 
        RAID_LOCKSERVER_ALREADY_LOCKED = "The server is already locked",
        RAID_LOCKSERVER_LOCKED_BY = "locked by %s",
        RAID_UNLOCKSERVER_HELP = "Unlocks the server",
        RAID_UNLOCKSERVER_NOT_LOCKED = "The server is not locked",
        RAID_UNLOCKSERVER_LOCKED_BY = "unlocked by %s",
        RAID_ALERT_SERVER_LOCKED_UNITL = "🔒 The server has been locked and will be unlocked %s (%s)",
        RAID_ALERT_SERVER_UNLOCKED = "🔓 The server has been unlocked (%s)",
        RAID_LOCK_EXPIRATION = "lock duration expired"
    }
}